-- Seed data: vocabulary words snapshot
-- ON CONFLICT (id) DO NOTHING makes every INSERT idempotent —
-- safe to run against a database that already has some or all of these rows.

SET client_encoding = 'UTF8';

INSERT INTO words (id, term, context, definition, usage_explanation, sample_sentences, register, related_words, category, created_at, status) VALUES ('e4d28f40-2dbb-48e1-aba3-8fa074d62e10', 'serendipity', 'I heard it in a movie about happy accidents', 'The occurrence of finding something good or valuable by happy accident, without having specifically searched for it', 'In the context of a movie about happy accidents, serendipity describes the pleasant and fortuitous coincidences that lead characters to unexpected positive outcomes, often used as a central theme in romantic or feel-good films', '["It was pure serendipity that she found her dream job while simply stopping for coffee one morning", "The scientific discovery was an act of serendipity, as the researcher had been looking for something else entirely", "Their meeting felt like serendipity — two strangers on the same train who turned out to be long-lost cousins"]', 'neutral', '["fortuitous", "coincidence", "fate", "happenstance"]', 'general', '2026-06-06 16:48:04.541736+00', 'new') ON CONFLICT (id) DO NOTHING;

INSERT INTO words (id, term, context, definition, usage_explanation, sample_sentences, register, related_words, category, created_at, status) VALUES ('c98d1593-c8ab-4f51-a530-7cc7d47f8421', 'chopped', 'when someone is chopped', 'To be suddenly dismissed, fired, or eliminated from a job, team, competition, or position', 'In the context of ''when someone is chopped,'' it refers to the abrupt removal or dismissal of a person from their role, position, or competition — popularized by TV shows like ''The Apprentice'' and ''Chopped'' where contestants are eliminated', '["He was chopped from the team after consistently missing deadlines.", "Three candidates were chopped in the first round of the competition.", "She didn''t expect to get chopped so early in the contest."]', 'slang', '["fired", "eliminated", "cut", "axed"]', 'social', '2026-06-06 16:49:43.926281+00', 'new') ON CONFLICT (id) DO NOTHING;

INSERT INTO words (id, term, context, definition, usage_explanation, sample_sentences, register, related_words, category, created_at, status) VALUES ('6702340f-9a54-4900-9b88-913e972aa8ed', 'clock', 'when someone tries to clock the other person', 'To look at someone intently.', 'In this context, ''clock'' is used as a verb meaning to strike or punch someone. The phrase ''tries to clock the other person'' describes an attempt to land a hard blow on another individual, commonly used when describing a fight or physical altercation.', '["He got so angry that he nearly clocked his opponent right in the jaw.", "She warned him that if he said one more thing, she would clock him.", "The bouncer almost clocked the rowdy customer before security intervened."]', 'slang', '["punch", "hit", "smack", "wallop"]', 'social', '2026-06-06 16:50:16.430014+00', 'mastered') ON CONFLICT (id) DO NOTHING;

INSERT INTO words (id, term, context, definition, usage_explanation, sample_sentences, register, related_words, category, created_at, status) VALUES ('3c9e6a3a-a358-4a58-9f8d-6eda367a5ff5', 'on the house', 'in a cafe, so meant free for customer', 'Provided free of charge by the establishment; paid for by the business rather than the customer', 'In a cafe or restaurant context, ''on the house'' means the item is being given to the customer at no cost, as a gesture of goodwill, hospitality, or apology from the owner or staff', '["The manager apologized for the long wait and said our desserts were on the house.", "After we mentioned it was our anniversary, the bartender brought over two cocktails on the house.", "The coffee came on the house because the kitchen had made a mistake with our order."]', 'idiomatic', '["complimentary", "free of charge", "freebie"]', 'idiom', '2026-06-06 17:08:07.597335+00', 'mastered') ON CONFLICT (id) DO NOTHING;

INSERT INTO words (id, term, context, definition, usage_explanation, sample_sentences, register, related_words, category, created_at, status) VALUES ('d34841d7-99c0-46f2-8545-5466e8d7d5f1', 'taste of your own medicine', 'in slang', 'An experience where someone receives the same unpleasant treatment they have inflicted on others, serving as a form of poetic justice or karmic retribution.', 'Used in slang and everyday speech to describe situations where a person who mistreats others ends up suffering the same kind of mistreatment, often with a tone of satisfaction or schadenfreude. It implies that the person deserved what they got.', '["He used to ghost people all the time, but when she ghosted him, he finally got a taste of his own medicine.", "The bully got a taste of his own medicine when the new kid stood up to him in front of everyone.", "She was always talking trash about her coworkers, so when they excluded her from the meeting, it was a taste of her own medicine."]', 'informal', '["karma", "what goes around comes around", "payback", "comeuppance"]', 'idiom', '2026-06-07 19:08:29.703133+00', 'new') ON CONFLICT (id) DO NOTHING;

INSERT INTO words (id, term, context, definition, usage_explanation, sample_sentences, register, related_words, category, created_at, status) VALUES ('3c99e8df-a202-4ddc-9b6f-6786b9d90c83', 'zesty', NULL, 'Having a strong, lively, and refreshing quality; full of energy, enthusiasm, or sharp flavor', '''Zesty'' is commonly used to describe food with a bright, tangy, or citrusy flavor, or more broadly to describe something that is lively, energetic, and invigorating. It carries a positive, upbeat connotation.', '["The chef added lemon zest to give the dish a zesty, refreshing finish.", "She brought a zesty enthusiasm to every project she tackled at work.", "This zesty salsa dressing is the perfect complement to a summer salad."]', 'informal', '["tangy", "vibrant", "lively", "piquant"]', 'general', '2026-06-07 19:08:45.163396+00', 'new') ON CONFLICT (id) DO NOTHING;

INSERT INTO words (id, term, context, definition, usage_explanation, sample_sentences, register, related_words, category, created_at, status) VALUES ('14a45749-371d-4fc5-a3a1-a3da3e693959', 'coin toss', 'how do you do a coin toss with three options; used when deciding in btw two things', 'The act of flipping a coin into the air and using whichever side lands face-up to make a random decision between two options, typically heads or tails.', 'Used as a method of random decision-making when choosing between two equally weighted options. The context highlights a limitation: a standard coin toss only works for two choices, not three. Figuratively, it can mean any situation that is essentially a 50/50 chance.', '["We couldn''t agree on where to eat, so we settled it with a coin toss.", "The game was so evenly matched that the outcome felt like a coin toss.", "They did a coin toss to decide who would go first in the presentation."]', 'neutral', '["heads or tails", "flip a coin", "random draw", "tiebreaker"]', 'general', '2026-06-07 19:10:31.849459+00', 'new') ON CONFLICT (id) DO NOTHING;

INSERT INTO words (id, term, context, definition, usage_explanation, sample_sentences, register, related_words, category, created_at, status) VALUES ('383c49c0-c3f4-4a19-9299-814bc1966954', 'buss', 'outside a restaurant, and someone said this already looks so buss', 'Trinidadian/Caribbean slang meaning excellent, amazing, impressive, or of high quality; something that stands out as really good', 'In the given context, ''buss'' is used to describe the restaurant''s appearance as looking impressive or outstanding even from the outside, suggesting it will be a great experience. It is commonly used in Trinidad and Tobago and wider Caribbean communities to express that something is top-tier or highly appealing.', '["That outfit you''re wearing tonight looks so buss, everyone is going to stare.", "The food at that new spot was buss — I''ve never tasted anything like it.", "When they walked into the venue, the decorations were so buss the whole crowd went quiet."]', 'slang', '["lit", "fire", "wicked", "dope"]', 'social', '2026-06-07 19:13:29.966026+00', 'new') ON CONFLICT (id) DO NOTHING;

INSERT INTO words (id, term, context, definition, usage_explanation, sample_sentences, register, related_words, category, created_at, status) VALUES ('e4afc910-c674-4581-9c44-0aee6bde4165', 'vibe check', 'office slang', 'An informal assessment of someone''s mood, attitude, energy, or overall feeling in a given moment or situation', 'In office slang, ''vibe check'' is used to gauge the general mood or attitude of a colleague, team, or meeting environment. It can be used to quickly assess whether someone is in a good or bad mood before approaching them, or to evaluate the overall atmosphere of a workplace situation.', '["Before the big presentation, Sarah did a quick vibe check on the team to see if everyone was feeling confident.", "How''s the vibe check on the new manager — is she easy to work with?", "Let me do a vibe check on the client before we pitch them the revised budget."]', 'slang', '["mood check", "temperature check", "pulse check", "read the room"]', 'social', '2026-06-07 19:41:04.962682+00', 'new') ON CONFLICT (id) DO NOTHING;

INSERT INTO words (id, term, context, definition, usage_explanation, sample_sentences, register, related_words, category, created_at, status) VALUES ('c07f1847-234f-4821-a95b-00012a35c47d', 'centrifuge', 'centrifuge area (talking about Intestellar movie)', 'A machine that uses rapid rotation to separate substances of different densities, or in sci-fi contexts, a rotating section of a spacecraft designed to simulate gravity through centrifugal force.', 'In the movie Interstellar, the ''centrifuge area'' refers to the rotating ring-shaped section of the Endurance spacecraft. This spinning structure creates artificial gravity for the crew by generating centrifugal force, mimicking the effect of gravitational pull so astronauts can live and move normally in space.', '["The crew gathered in the centrifuge area of the Endurance to eat their meals, as the rotating section provided enough artificial gravity to keep food on their plates.", "Scientists use a centrifuge in the laboratory to separate blood components by spinning samples at thousands of revolutions per minute.", "The space station''s centrifuge module was critical for preventing the long-term bone and muscle deterioration that astronauts experience in zero gravity."]', 'neutral', '["artificial gravity", "rotation", "centrifugal force", "spacecraft"]', 'technology', '2026-06-07 19:47:56.351158+00', 'new') ON CONFLICT (id) DO NOTHING;

INSERT INTO words (id, term, context, definition, usage_explanation, sample_sentences, register, related_words, category, created_at, status) VALUES ('54058f36-ba3d-478e-877d-5d99fcfc8b30', 'wholesome', NULL, '', '', '[]', 'neutral', '[]', 'general', '2026-06-08 00:08:41.368529+00', 'new') ON CONFLICT (id) DO NOTHING;

INSERT INTO words (id, term, context, definition, usage_explanation, sample_sentences, register, related_words, category, created_at, status) VALUES ('33f68a6f-ec65-4abc-ae2e-5ef5849c6263', 'gesture', NULL, '', '', '[]', 'neutral', '[]', 'general', '2026-06-08 00:08:44.025285+00', 'new') ON CONFLICT (id) DO NOTHING;

INSERT INTO words (id, term, context, definition, usage_explanation, sample_sentences, register, related_words, category, created_at, status) VALUES ('d837fc77-3a51-4ebe-9b47-6695d1eba018', 'diabolical', 'when people are playing guess celebrities and the person who couldn''t guess his said "why are you giving this diabolical"', 'In this context, ''diabolical'' is British slang meaning terrible, awful, or of very poor quality. It can also mean extremely difficult or confusing. In its original sense, it means relating to the devil or something evil.', 'In the context given, the person is complaining that the clues or hints being given are terrible and unhelpful — essentially saying ''why are you giving such awful/useless clues?'' This is a very common British informal usage where ''diabolical'' simply means shockingly bad or poor quality.', '["The directions he gave me were diabolical — I ended up completely lost.", "Her impression of the celebrity was diabolical; nobody could guess who it was supposed to be.", "The service at that restaurant was absolutely diabolical, we waited an hour for our food."]', 'informal', '["terrible", "atrocious", "dreadful", "rubbish"]', 'social', '2026-06-08 00:09:34.411798+00', 'new') ON CONFLICT (id) DO NOTHING;
